# Generated by Django 3.1.5 on 2021-02-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0003_auto_20210128_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'Userpreference', 'verbose_name_plural': 'Userpreferences'},
        ),
    ]
