version: '3'

services:
  web:
    environment:
        - debug=True
        - secret_key=')y6)n^6($nw^tpyso8v!6#*jc69ht4l^=njpot)od2*ue_7i-4'
        - db='postgresql'
    build: .
    command: python MoneyTracker/manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
