name: MoneyTracker Test

on:
    push:
        branches:
            - master

    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up python 3.7
              uses: actions/setup-python@v2
              with:
                python-version: 3.7
            - name: Install dependency
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements-dev.txt
            - name: Lint with flake8
              run: |
                  flake8
            - name: Coverage report
              run: |
                  coverage run MoneyTracker/manage.py test
                  coverage report
            - name: Django testing
              run: |
                  python3 MoneyTracker/manage.py test MoneyTracker
