name: MoneyTracker Test

on:
    push:
        branches:
            - master

    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up python 3.7
              uses: actions/setup-python@v2
              with:
                python-version: 3.7
            - name: Install dependency
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Lint with flake8
              run: |
                  pip install flake8
                  flake8
            - name: Coverage report
              env:
                  secret_key: ')y6)n^6($nw^tpyso8v!6#*jc69ht4l^=njpot)od2*ue_7i-4'
                  debug: True
                  db: 'sqlite3'
              run: |
                  pip install coverage
                  coverage run MoneyTracker/manage.py test
                  coverage report
            - name: Django testing
              run: |
                  python3 MoneyTracker/manage.py test MoneyTracker
