name: MoneyTracker


on:
  pull_request:
  push:
    branches:
      - master
      - develop
job:
  build:
      name: Secutity Check
      run-on: ubuntu-letest
        steps:
          - uses: victoriadrake/django-security-check@v1.1.0
